export const FACEBOOK_LOGIN = "FACEBOOK_LOGIN"
export const FACEBOOK_LOGIN_SUCCESS = "FACEBOOK_LOGIN_SUCCESS"
export const GOOGLE_LOGIN = "GOOGLE_LOGIN"
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS"