export const FETCH_COLLECTIBLES               = "FETCH_COLLECTIBLES"
export const FETCH_COLLECTIBLES_SUCCESS       = "FETCH_COLLECTIBLES_SUCCESS"
export const FETCH_COLLECTIBLES_FAILURE       = "FETCH_COLLECTIBLES_FAILURE"

export const FETCH_SERIES                     = "FETCH_SERIES"
export const FETCH_SERIES_SUCCESS             = "FETCH_SERIES_SUCCESS"
export const FETCH_SERIES_FAILURE             = "FETCH_SERIES_FAILURE"